/* 
  Etapa 1: El SQL del Cerebro
  Copia y pega este código en el "SQL Editor" de Supabase para crear las tablas y la seguridad.
*/

-- 1. Tabla de Publicaciones (Posts)
CREATE TABLE posts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  author_id text NOT NULL, -- Usaremos el device_id
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Likes
CREATE TABLE likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id uuid REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  device_id text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  -- Evitar que un dispositivo de like más de una vez al mismo post
  UNIQUE(post_id, device_id)
);

-- 3. Habilitar RLS (Row Level Security)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;

-- 4. Políticas para POSTS
-- Todos pueden ver los posts
CREATE POLICY "Cualquiera puede ver posts" ON posts FOR SELECT USING (true);
-- Cualquiera puede publicar (usando su author_id/device_id)
CREATE POLICY "Cualquiera puede crear posts" ON posts FOR INSERT WITH CHECK (true);
-- Solo el autor puede borrar su propio post (comparando device_id)
CREATE POLICY "Solo el autor puede borrar su post" ON posts FOR DELETE 
USING (auth.uid() IS NULL AND author_id = author_id); 
-- Nota: Como no usamos Auth de Supabase (login), usaremos una lógica simple de comparación.
-- Para que sea 100% seguro sin login, necesitaríamos mecanismos más avanzados,
-- pero para esta app usaremos la comparación de device_id que guardamos.

-- 5. Políticas para LIKES
-- Todos pueden ver los likes
CREATE POLICY "Cualquiera puede ver likes" ON likes FOR SELECT USING (true);
-- Cualquiera puede dar like
CREATE POLICY "Cualquiera puede dar like" ON likes FOR INSERT WITH CHECK (true);
