/* 
  🚀 Twiter Padaguan - Setup Consolidado
  Copia y pega este código en el "SQL Editor" de Supabase.
*/

-- 1. Tablas principales
CREATE TABLE IF NOT EXISTS public.posts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  content text NOT NULL,
  author_id text NOT NULL,
  media_url text,
  media_type text,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id uuid REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  device_id text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(post_id, device_id)
);

CREATE TABLE IF NOT EXISTS public.comments (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  post_id uuid REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  author_id text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.identidades_padaguan (
  device_id text PRIMARY KEY,
  username text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    device_id TEXT NOT NULL,
    subscription_json JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Habilitar RLS
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE identidades_padaguan ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acceso (Simplificadas para ambiente abierto)
-- POSTS
DROP POLICY IF EXISTS "Select posts" ON posts;
CREATE POLICY "Select posts" ON posts FOR SELECT USING (true);
DROP POLICY IF EXISTS "Insert posts" ON posts;
CREATE POLICY "Insert posts" ON posts FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Delete posts" ON posts;
CREATE POLICY "Delete posts" ON posts FOR DELETE USING (author_id = author_id);

-- LIKES
DROP POLICY IF EXISTS "Select likes" ON likes;
CREATE POLICY "Select likes" ON likes FOR SELECT USING (true);
DROP POLICY IF EXISTS "Insert likes" ON likes;
CREATE POLICY "Insert likes" ON likes FOR INSERT WITH CHECK (true);

-- COMMENTS
DROP POLICY IF EXISTS "Select comments" ON comments;
CREATE POLICY "Select comments" ON comments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Insert comments" ON comments;
CREATE POLICY "Insert comments" ON comments FOR INSERT WITH CHECK (true);

-- IDENTIDADES
DROP POLICY IF EXISTS "Select identidades" ON identidades_padaguan;
CREATE POLICY "Select identidades" ON identidades_padaguan FOR SELECT USING (true);
DROP POLICY IF EXISTS "Upsert identidades" ON identidades_padaguan;
CREATE POLICY "Upsert identidades" ON identidades_padaguan FOR ALL USING (true) WITH CHECK (true);

-- PUSH
DROP POLICY IF EXISTS "Push access" ON push_subscriptions;
CREATE POLICY "Push access" ON push_subscriptions FOR ALL USING (true) WITH CHECK (true);
